title: ProductStatusEnum
type: string
description: "進捗¥n\
              IN_STOCK:在庫あり¥n\
              ON_LEASE:レンタル中¥n\
              BLOKEN:破損\
              "
enum:
  - IN_STOCK
  - ON_LEASE
  - BLOKEN
example: IN_STOCK