/**
 * OpenAPI Template
 * Template of split OpenAPI with validator
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ソーシャル認証
 */
export type SocialEnum = 'GOOGLE' | 'AMAZON';

export const SocialEnum = {
    Google: 'GOOGLE' as SocialEnum,
    Amazon: 'AMAZON' as SocialEnum
};

