/**
 * OpenAPI Template
 * Template of split OpenAPI with validator
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StatusEnum = 'EDIT' | 'WAITING' | 'APPLIED';

export const StatusEnum = {
    Edit: 'EDIT' as StatusEnum,
    Waiting: 'WAITING' as StatusEnum,
    Applied: 'APPLIED' as StatusEnum
};

