title: ProductReviewsRequest
type: object
properties:
  product_id:
    type: integer
    description: 商品ID
    example: 1
  userId:
    type: integer
    description: ユーザーID
    example: 1
  title:
    type: string
    description: タイトル
    maxLength: 128
    example: 'タイトル'
  text:
    type: string
    description: レビュー内容
    example: 'レビュー内容'
  evaluation:
    type: integer
    description: 評価(10段階)
    example: 1

required:
  - product_id
  - userId
  - title
  - text
  - evaluation
