get:
  tags:
    - task
  summary: Find task by id
  description: Return a single Task
  operationId: getTaskById
  parameters:
    - name: id
      in: path
      description: task id
      required: true
      schema:
        type: integer
  responses:
    200:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: ../../schemas/Tasks.yaml
#            allOf:
#              - $ref: ../../schemas/Pagination.yaml
#              - type: object
#                properties:
#                  data:
#                    type: array
#                    items:
#                      $ref: ../../schemas/Task.yaml