/**
 * OpenAPI Template
 * Template of split OpenAPI with validator
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Task {
    /**
    * ID of the task
    */
    'id'?: number;
    /**
    * Name of the task
    */
    'name'?: string;
    /**
    * Whether the task is completed
    */
    'isCompleted'?: boolean;
    /**
    * Deadline of the task
    */
    'deadline'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "isCompleted",
            "baseName": "is_completed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deadline",
            "baseName": "deadline",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Task.attributeTypeMap;
    }

    public constructor() {
    }
}

