openapi: 3.0.0
info:
  title: OpenAPI Template
  description: Template of split OpenAPI with validator
  version: 1.0.0
servers:
  - url: "{server}"
    description: URL of the server
    variables:
      server:
        default: http://localhost:3000
paths:
  /users:
    $ref: ./paths/users/index.yml
  '/users/{id}':
    $ref: ./paths/users/id/index.yml
  '/users/{id}/email':
    $ref: ./paths/users/id/email/index.yml
components:
  schemas:
    User:
      $ref: ./schemas/models/User.yml
    Address:
      $ref: ./schemas/models/Address.yml
    Credit:
      $ref: ./schemas/models/Credit.yml
    UserResponse:
      $ref: ./responses/UserResponse.yml
    UsersResponse:
      $ref: ./responses/UsersResponse.yml