openapi: 3.0.0
info:
  title: OpenAPI Template
  description: Template of split OpenAPI with validator
  version: 1.0.0
servers:
  - url: "{server}"
    description: URL of the server
    variables:
      server:
        default: http://localhost:3000
paths:
  # 認証
  /sanctum/csrf-cookie:
    $ref: ./paths/sanctum/csrf-cookie/index.yml
  /auth/signin:
    $ref: ./paths/auth/signin/index.yml
  /auth/signout:
    $ref: ./paths/auth/signout/index.yml
  /auth/signup:
    $ref: ./paths/auth/signup/index.yml

  # ログインユーザの情報取得
  '/my/user':
    $ref: ./paths/my/user/index.yml
  '/my/user/email':
    $ref: ./paths/my/user/email/index.yml
  '/my/user/password':
    $ref: ./paths/my/user/password/index.yml
  '/my/user/withdrawal':
    $ref: ./paths/my/user/withdrawal/index.yml
  '/my/address/default':
    $ref: ./paths/my/address/default/index.yml
  '/my/address/idDefault':
    $ref: ./paths/my/address/idDefault/index.yml
  '/my/addresses':
    $ref: ./paths/my/addresses/index.yml
  '/my/orders':
    $ref: ./paths/my/orders/index.yml
    
  # 住所
  '/addresses':
    $ref: ./paths/addresses/index.yml
  '/addresses/{addressId}':
    $ref: ./paths/addresses/addressId/index.yml
    
  # 商品原本検索
  '/productOrigins':
    $ref: ./paths/productOrigins/index.yml
  '/my/admin/adminAuthorities':
    $ref: ./paths/my/admin/adminAuthorities/index.yml

  '/ジャンル':
    $ref: ./paths/genres/index.yml

  # 商品レビュー
  '/productReviews':
    $ref: ./paths/productReviews/index.yml
  # 商品レビュー
  '/deliverTimes':
    $ref: ./paths/deliverTimes/index.yml
  # お問い合わせ
  '/inquiries':
    $ref: ./paths/inquiries/index.yml

  '/users/{emailReissueToken}/password/reissue':
    $ref: ./paths/users/emailReissueToken/password/reissue/index.yml
  '/users/{email}/password/reissue':
    $ref: ./paths/users/email/password/reissue/index.yml
  # お知らせ
  '/notices':
    $ref: ./paths/notices/index.yml
  '/notices/{noticeId}':
    $ref: ./paths/notices/noticeId/index.yml
  # おすすめ商品
  '/recommendProducts':
    $ref: ./paths/recommendProducts/index.yml
  # クライアントシークレットの発行
  '/my/stripe/clientSecret':
    $ref: ./paths/my/stripe/clientSecret.yml
  # 登録済みクレジットカード情報
  '/my/credits':
    $ref: ./paths/my/credits/index.yml
  # stripe顧客ID取得
  '/my/credits/id':
    $ref: ./paths/my/credits/id/index.yml


  # 管理API群
  # 管理権限
  '/admin/adminAuthorities':
    $ref: ./paths/admin/adminAuthorities/index.yml
  '/admin/adminAuthorities/{adminAuthorityId}':
    $ref: ./paths/admin/adminAuthorities/adminAuthorityId/index.yml
  # 管理権限マスタ
  '/admin/roles':
    $ref: ./paths/admin/roles/index.yml
  '/admin/roles/{roleId}':
    $ref: ./paths/admin/roles/roleId/index.yml
  # 配達時間マスタ
  '/admin/deliverTimes':
    $ref: ./paths/admin/deliverTimes/index.yml
  '/admin/deliverTimes/{deliverTimeId}':
    $ref: ./paths/admin/deliverTimes/deliverTimeId/index.yml
  # 配達情報
  '/admin/delivers':
    $ref: ./paths/admin/delivers/index.yml
  '/admin/delivers/{deliverId}':
    $ref: ./paths/admin/delivers/deliverId/index.yml
  # メーカー情報
  '/admin/makers':
    $ref: ./paths/admin/makers/index.yml
  '/admin/makers/{makerId}':
    $ref: ./paths/admin/makers/makerId/index.yml
  # 商品ランク情報
  '/admin/productRanks':
    $ref: ./paths/admin/productRanks/index.yml
  '/admin/productRanks/{productRankId}':
    $ref: ./paths/admin/productRanks/productRankId/index.yml
  # お知らせ
  '/admin/notices':
    $ref: ./paths/admin/notices/index.yml
  '/admin/notices/{noticeId}':
    $ref: ./paths/admin/notices/noticeId/index.yml
  # お問い合わせ種別
  '/admin/inquiryTypes':
    $ref: ./paths/admin/inquiryTypes/index.yml
  '/admin/inquiryTypes/{inquiryTypeId}':
    $ref: ./paths/admin/inquiryTypes/inquiryTypeId/index.yml
  # お問い合わせ
  '/admin/inquiries':
    $ref: ./paths/admin/inquiries/index.yml
  '/admin/inquiries/{inquiryId}':
    $ref: ./paths/admin/inquiries/inquiryId/index.yml

components:
  schemas:
    User:
      $ref: ./schemas/models/User.yml
    Address:
      $ref: ./schemas/models/Address.yml
    Credit:
      $ref: ./schemas/models/Credit.yml
    CreditDetail:
      $ref: ./schemas/models/CreditDetail.yml
    AdminAuthority:
      $ref: ./schemas/models/AdminAuthority.yml
    Deliver:
      $ref: ./schemas/models/Deliver.yml
    DeliverTime:
      $ref: ./schemas/models/DeliverTime.yml
    Demand:
      $ref: ./schemas/models/Demand.yml
    Genre:
      $ref: ./schemas/models/Genre.yml
    Inquiry:
      $ref: ./schemas/models/Inquiry.yml
    InquiryType:
      $ref: ./schemas/models/InquiryType.yml
    Maker:
      $ref: ./schemas/models/Maker.yml
    Notice:
      $ref: ./schemas/models/Notice.yml
    Order:
      $ref: ./schemas/models/Order.yml
    Product:
      $ref: ./schemas/models/Product.yml
    ProductImage:
      $ref: ./schemas/models/ProductImage.yml
    ProductOrigin:
      $ref: ./schemas/models/ProductOrigin.yml
    ProductRank:
      $ref: ./schemas/models/ProductRank.yml
    ProductReview:
      $ref: ./schemas/models/ProductReview.yml
    ProductType:
      $ref: ./schemas/models/ProductType.yml
    Role:
      $ref: ./schemas/models/Role.yml
    MaskCard:
      $ref: ./schemas/models/MaskCard.yml
    AuthSignupResponse:
      $ref: ./responses/auth/AuthSignupResponse.yml
    UserShowResponse:
      $ref: ./responses/users/UserShowResponse.yml
    UsersResponse:
      $ref: ./responses/users/UsersResponse.yml
