openapi: 3.0.0
info:
  title: OpenAPI Template
  description: Template of split OpenAPI with validator
  version: 1.0.0
servers:
  - url: "{server}"
    description: URL of the server
    variables:
      server:
        default: http://localhost:3000
paths:
  # 認証
  /auth/signin:
    $ref: ./paths/auth/signin/index.yml
  /auth/signout:
    $ref: ./paths/auth/signout/index.yml
#  /auth/signup:
#    $ref: ./paths/auth/signup/index.yml

  # ユーザ
  '/users':
    $ref: ./paths/users/index.yml
  '/users/{userId}':
    $ref: ./paths/users/userId/index.yml
  '/users/{userId}/email':
    $ref: ./paths/users/userId/email/index.yml
  '/users/{userId}/password':
    $ref: ./paths/users/userId/password/index.yml
  '/users/{userId}/withdrawal':
    $ref: ./paths/users/userId/withdrawal/index.yml
  '/users/{email}/password/reissue':
    $ref: ./paths/users/email/password/reissue/index.yml
  '/users/{email_reissue_token}/password/reissue':
    $ref: ./paths/users/emailReissueToken/password/reissue/index.yml

  # 住所
  '/addresses':
    $ref: ./paths/addresses/index.yml
  '/users/{userId}/addresses/isDefault':
    $ref: ./paths/users/userId/addresses/isDefault/index.yml
components:
  schemas:
    User:
      $ref: ./schemas/models/User.yml
    Address:
      $ref: ./schemas/models/Address.yml
    Credit:
      $ref: ./schemas/models/Credit.yml
    CreditDetail:
      $ref: ./schemas/models/CreditDetail.yml
    AuthSignupResponse:
      $ref: ./responses/auth/AuthSignupResponse.yml
    UserResponse:
      $ref: ./responses/users/UserResponse.yml
    UserShowResponse:
      $ref: ./responses/users/UserShowResponse.yml
    UsersResponse:
      $ref: ./responses/users/UsersResponse.yml
