openapi: 3.0.0
info:
  title: OpenAPI Template
  description: Template of split OpenAPI with validator
  version: 1.0.0
servers:
  - url: "{server}"
    description: URL of the server
    variables:
      server:
        default: http://localhost:3000
paths:
  /auth/signin:
    $ref: ./paths/auth/signin/index.yml
  /users:
    $ref: ./paths/users/index.yml
  '/users/{userId}':
    $ref: ./paths/users/userId/index.yml
  '/users/{userId}/email':
    $ref: ./paths/users/userId/email/index.yml
components:
  schemas:
    User:
      $ref: ./schemas/models/User.yml
    Address:
      $ref: ./schemas/models/Address.yml
    Credit:
      $ref: ./schemas/models/Credit.yml
    CreditDetail:
      $ref: ./schemas/models/CreditDetail.yml
    AuthSignupResponse:
      $ref: ./responses/auth/AuthSignupResponse.yml
    UserResponse:
      $ref: ./responses/users/UserResponse.yml
    UserShowResponse:
      $ref: ./responses/users/UserShowResponse.yml
    UsersResponse:
      $ref: ./responses/users/UsersResponse.yml
