title: ProductReview
type: object
properties:
  id:
    type: integer
    description: 商品レビューID
    example: 1
  productId:
    type: integer
    description: 商品ID
    example: 1
  userId:
    type: integer
    description: ユーザーID
    example: 1
  title:
    type: string
    description: タイトル
    maxLength: 128
    example: "最高評価"
  text:
    type: string
    description: レビュー内容
    example: "品質もよく満足いくレンタルでした"
  evaluation:
    type: integer
    description: 評価(5段階)
    example: 5
  createdAt:
    type: string
    format: date-time
    description: 作成日
    example: "2023-03-14 19:32:41"
  updatedAt:
    type: string
    format: date-time
    description: 更新日
    example: "2023-03-15 18:03:09"
  createdBy:
    type: integer
    description: 作成者
    example: 1
  updatedBy:
    type: integer
    description: 更新者
    example: 1
required:
  - id
  - productId
  - userId
  - title
  - text
  - evaluation
  - createdAt
  - updatedAt
  - createdBy
  - updatedBy
