title: Product
type: object

properties:
  id:
    type: integer
    description: 住所ID
    example: 1
  userId:
    type: integer
    description: ユーザID
    example: 1
  productOriginId:
    type: integer
    description: 商品原本ID
    example: 1
  productTypeId:
    type: integer
    description: 商品タイプID
    example: 1
  name:
    type: string
    description: 商品名
    example: 【完品】PS5 デジタルエディション
  price:
    type: integer
    description: 商品ランクID
    example: 60000
  stripePlanId:
    type: integer
    description: 商品ランクID
    example: XXXXXXXXXXX
  status:
    type: integer
    description: ステータス
    example: IN_STOCK
  createdAt:
    type: string
    format: date-time
    description: 作成日
    example: "2023-03-14 19:32:41"
  updatedAt:
    type: string
    format: date-time
    description: 更新日
    example: "2023-03-15 18:03:09"
  createdBy:
    type: integer
    description: 作成者
    example: 1
  updatedBy:
    type: integer
    description: 更新者
    example: 1
required:
  - id
  - userId
  - productOriginId
  - productTypeId
  - name
  - price
  - stripePlanId
  - status
  - createdAt
  - updatedAt
  - createdBy
  - updatedBy
