title: ProductRanksResponse
type: object
allOf:
  - $ref: ../../../schemas/models/Pagination.yml
  - properties:
      data:
        type: array
        items:
          $ref: ../../../schemas/models/ProductRank.yml
required:
  - data